### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [joaaoeu/rocketbook#1]
Hi @joaaoeu I am contributing to the open source community by designing logos. If you want, I can design a logo for your repo. Actually I have the idea of ​​a minimalist and functional logo in my mind. What do you think?

**Comment by joaovbrandon** [comment]
Hi @reallinfo. This is just a project part of a course that I did and it don't will advance, but if you wanna you can contribute whit the logo. Thanks :)

**Comment by reallinfo** [comment]
Since the template is blue, I preferred the blue color. You can suggest another color if you like.

![rocketbook](https://user-images.githubusercontent.com/36298335/54821192-81f94f00-4cb2-11e9-98db-d2c4605f5210.jpg)

**Comment by joaovbrandon** [comment]
I loved the concept idea, but don't you think we should have a white version?

**[Dark Version]**
![rocketbook-print1](https://user-images.githubusercontent.com/6677405/54827866-b01a6700-4c91-11e9-9d4a-a19cadde9ce8.png)

**[Light Version]**
![rocketbook-print2](https://user-images.githubusercontent.com/6677405/54827867-b01a6700-4c91-11e9-9371-0726a67ad3f2.png)

**Comment by reallinfo** [comment]
Oh ofcourse, I applied blue color to put it in the readme file. But I think your idea is better :) If you want, i can send a pr for white color logo.

**Comment by joaovbrandon** [comment]
Yeah, I noticed that. If you could, please send a PR. And put the original in the README too!

**Comment by reallinfo** [comment]
I sent a pr. You can contact me if you need any logo. Have a nice day!
